# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c8b1b902-d240-4b48-9af5-913a5c6f6e63";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c8b1b902-d240-4b48-9af5-913a5c6f6e63".device = "/dev/disk/by-uuid/c8b1b902-d240-4b48-9af5-913a5c6f6e63";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/59D7-79C6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-9019da06-827c-4c90-9b68-5c0099d89a13"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
