# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-52534c51-7f6d-405d-b8c5-a304fd76ba85";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-52534c51-7f6d-405d-b8c5-a304fd76ba85".device = "/dev/disk/by-uuid/52534c51-7f6d-405d-b8c5-a304fd76ba85";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3D02-9638";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-e72a7a07-20ec-444d-a711-c693cf9ed082"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
